name: Blacksmith
author: aPunch, jrbudda, HurricanKai, Verex
version: 1.14
main: net.apunch.blacksmith.BlacksmithPlugin
depend: [Citizens, Vault]
softdepend: [HyperConomy]

api-version: 1.14

commands:
  blacksmithreload:
    permission: blacksmith.reload
    description: Reloads the config file for Blacksmith

permissions:
  blacksmith.reload:
    description: Reloads the config file for Blacksmith
  blacksmith.reforge:
    description: Allows use of the reforge NPC.